services:
  # Database initialization service
  portfoliodb-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        POSTGRES_UID: ${POSTGRES_UID:-1100}
        POSTGRES_GID: ${POSTGRES_GID:-1100}
    container_name: portfoliodb-init
    volumes:
      - /tmp/portfoliodb/data:/var/lib/postgresql/17/main
    environment:
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=portfoliodb
      - POSTGRES_PASSWORD=portfoliodb_dev_password
      - POSTGRES_DB=portfoliodb
      - DB_ACTION=${DB_ACTION:-init}
    command: [ "/opt/portfoliodb/scripts/init-db.sh" ]
    profiles:
      - init

  # Main development service
  portfoliodb-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        POSTGRES_UID: ${POSTGRES_UID:-1100}
        POSTGRES_GID: ${POSTGRES_GID:-1100}
    container_name: portfoliodb-dev
    ports:
      - "50001:50001"
      - "5432:5432"
    volumes:
      - ../external/portfoliodb:/opt/portfoliodb/src
      - /tmp/portfoliodb/data:/var/lib/postgresql/17/main
      - /tmp/portfoliodb/logs/postgresql:/var/log/postgresql
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://portfoliodb:portfoliodb_dev_password@localhost:5432/portfoliodb
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
    restart: unless-stopped

  # Test service
  portfoliodb-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        POSTGRES_UID: ${POSTGRES_UID:-1100}
        POSTGRES_GID: ${POSTGRES_GID:-1100}
    container_name: portfoliodb-test
    volumes:
      - ../external/portfoliodb:/opt/portfoliodb/src
      - /tmp/portfoliodb/logs/test:/tmp/portfoliodb/logs/test
    environment:
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=portfoliodb
      - POSTGRES_PASSWORD=portfoliodb_test_password
      - POSTGRES_DB=portfoliodb_test
      - DATABASE_URL=postgres://portfoliodb:portfoliodb_test_password@localhost:5432/portfoliodb_test
      - RUST_LOG=debug
      - RUST_BACKTRACE=${RUST_BACKTRACE:-0}
    command: [ "/opt/portfoliodb/scripts/test.sh" ]
    profiles:
      - test

volumes:
  postgres_data:
    driver: local
