services:
  # Database initialization service
  portfoliodb-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: init
      args:
        UID: ${UID:-1100}
        GID: ${GID:-1100}
    container_name: portfoliodb-init
    volumes:
      - ${PORTFOLIODB_REPO_DIR:-../external/portfoliodb}:/opt/portfoliodb/src
      - ${POSTGRES_DATA_DIR:-../run/postgres/data}:/var/lib/postgresql/17
      - ${POSTGRES_ETC_DIR:-../run/postgres/etc}:/etc/postgresql/17
    environment:
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=portfoliodb
      - DB_ACTION=${DB_ACTION:-init}

  # Main development service
  portfoliodb-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: ${UID:-1100}
        GID: ${GID:-1100}
    container_name: portfoliodb-dev
    ports:
      - "50001:50001"
      - "5432:5432"
    volumes:
      - ${PORTFOLIODB_REPO_DIR:-../external/portfoliodb}:/opt/portfoliodb/src
      - ${POSTGRES_DATA_DIR:-../run/postgres/data}:/var/lib/postgresql/17
      - ${POSTGRES_ETC_DIR:-../run/postgres/etc}:/etc/postgresql/17
      - ${POSTGRES_LOGS_DIR:-../run/postgres/logs}:/var/log/postgresql
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://dev:dev@localhost:5432/portfoliodb
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
    restart: unless-stopped

  # Test service
  portfoliodb-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        UID: ${UID:-1100}
        GID: ${GID:-1100}
    container_name: portfoliodb-test
    volumes:
      - ${PORTFOLIODB_REPO_DIR:-../external/portfoliodb}:/opt/portfoliodb/src
      - ${POSTGRES_TEST_LOGS_DIR:-../run/test/logs/postgres}:/var/log/postgresql
    environment:
      - RUST_BACKTRACE=${RUST_BACKTRACE:-0}
      - TEST_FILES=${TEST_FILES:-}

volumes:
  postgres_data:
    driver: local
