services:
  # Database initialization service
  portfoliodb-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: portfoliodb-init
    volumes:
      - /tmp/portfoliodb/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATA_DIR=/var/lib/postgresql/data
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=portfoliodb
      - POSTGRES_PASSWORD=portfoliodb_dev_password
      - POSTGRES_DB=portfoliodb
      - DB_ACTION=${DB_ACTION:-init}
    command: ["/opt/portfoliodb/scripts/init-db.sh"]
    profiles:
      - init

  # Main development service
  portfoliodb-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: portfoliodb-dev
    ports:
      - "50001:50001"
      - "5432:5432"
    volumes:
      - ./bin/portfoliodb:/opt/portfoliodb/portfoliodb
      - /tmp/portfoliodb/data:/var/lib/postgresql/data
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://portfoliodb:portfoliodb_dev_password@localhost:5432/portfoliodb
      - POSTGRES_DATA_DIR=/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local 